site_name: Python 2022
theme:
  name: 'material'
  logo: images/logo.png
  favicon: images/favicon.ico
  features:
    - navigation.tabs
    - navigation.tabs.sticy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Inicio: index.md
  - Teorías:
    - Recursos: 01_teorias/recursos.md
    - Clase 1: 01_teorias/clase_01.ipynb
    - Clase 1-1: 01_teorias/clase_01_1.ipynb
    - Clase 2: 01_teorias/clase_02.ipynb
    - Clase 2-1: 01_teorias/clase_02_1.ipynb
    - Clase 3: 01_teorias/clase03.ipynb
    - Clase 3-1: 01_teorias/clase03_1.ipynb
    - Clase 4: 01_teorias/clase04.ipynb
    - Clase 4-1: 01_teorias/clase04_1.ipynb
  - Práctica:
    - Recursos: 02_practicas/recursos.md
    - Práctica 1: 02_practicas/practica01.ipynb
  - Explicaciones: 03_explicaciones.md
  - Guías:
    - Comandos: guias/01_commands.md
    - Ssh: guias/02_ssh.md
    - Ssh Gitlab: guias/03_ssh_gitlab.md
    - Instalar Git: guias/04_instalar_git.md
    - Git básico: guias/05_git_basico.md
    - Instalar Python: guias/06_instalar_python.md
    - Entornos Virtuales: guias/07_entornos_virtuales.md
    - Manejo de Paquetes: guias/08_manejo_de_paquetes.md
    - Guías de Estilo: guias/09_guias_de_estilo.md
    - Merge Requests en Gitlab: guias/10_merge_request.md
    - Jupyter Notebook: guias/11_jupyter_notebook.md

markdown_extensions: 
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - admonition
  - codehilite
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
plugins:
  - mkdocs-video
  - mkdocs-jupyter:
      ignore_h1_titles: True
      execute: False
